#!/usr/bin/env python3
"""Install and verify OpenScreen's signed macOS native payloads.

The product source is MIT-licensed, but its macOS capture/compositor payloads
are generated by the upstream OpenScreen release build.  This helper fetches
only the pinned official release archive, verifies its SHA-256 digest before
opening it, extracts only the required native files, and records their hashes.
It never inspects or copies the installed application in /Applications.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import platform
import shutil
import stat
import subprocess
import sys
import tempfile
import time
import urllib.request
import zipfile
from pathlib import Path
from typing import Any


COMMAND = "native-setup"
CONFIG_PATH = Path(__file__).resolve().parents[1] / "native-payloads.json"
MARKER_NAME = ".mega-recorder-native.json"


def emit(payload: dict[str, Any]) -> None:
    print(json.dumps(payload, separators=(",", ":")), flush=True)


def read_config() -> dict[str, Any]:
    try:
        value = json.loads(CONFIG_PATH.read_text(encoding="utf-8"))
    except (OSError, ValueError) as error:
        raise RuntimeError(f"Unable to read native payload manifest: {CONFIG_PATH}: {error}") from error
    if not isinstance(value, dict):
        raise RuntimeError(f"Native payload manifest is not an object: {CONFIG_PATH}")
    return value


def repo_path(value: str) -> Path:
    path = Path(value).expanduser().resolve()
    if not (path.is_dir() and (path / "package.json").is_file()):
        raise ValueError(f"Product checkout is invalid: {path}")
    return path


def host_tag() -> tuple[str | None, dict[str, str]]:
    if sys.platform != "darwin":
        return None, {
            "platform": sys.platform,
            "machine": platform.machine(),
            "code": "NATIVE_PLATFORM_UNSUPPORTED",
        }
    machine = platform.machine().lower()
    if machine in {"arm64", "aarch64"}:
        return "darwin-arm64", {"platform": "darwin", "machine": machine, "architecture": "arm64"}
    if machine in {"x86_64", "amd64", "x64"}:
        return "darwin-x64", {"platform": "darwin", "machine": machine, "architecture": "x64"}
    return None, {
        "platform": "darwin",
        "machine": machine,
        "code": "NATIVE_ARCH_UNSUPPORTED",
    }


def sha256(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as handle:
        for chunk in iter(lambda: handle.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def native_dir(repo: Path, tag: str) -> Path:
    return repo / "electron" / "native" / "bin" / tag


def cache_dir() -> Path:
    configured = os.environ.get("MEGA_RECORDER_NATIVE_CACHE")
    if configured:
        return Path(configured).expanduser().resolve()
    base = os.environ.get("XDG_CACHE_HOME")
    return (Path(base).expanduser() if base else Path.home() / ".cache") / "mega-recorder" / "native"


def marker_path(destination: Path) -> Path:
    return destination / MARKER_NAME


def load_marker(destination: Path) -> dict[str, Any] | None:
    try:
        value = json.loads(marker_path(destination).read_text(encoding="utf-8"))
    except (OSError, ValueError):
        return None
    return value if isinstance(value, dict) else None


def executable_ok(path: Path) -> bool:
    try:
        mode = path.stat().st_mode
    except OSError:
        return False
    return path.is_file() and bool(mode & (stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH))


def codesign_status(path: Path) -> dict[str, Any]:
    if sys.platform != "darwin":
        return {"checked": False, "valid": None}
    try:
        completed = subprocess.run(
            ["codesign", "--verify", "--strict", "--verbose=2", str(path)],
            text=True,
            stdout=subprocess.PIPE,
            stderr=subprocess.PIPE,
            check=False,
        )
    except OSError as error:
        return {"checked": False, "valid": None, "error": str(error)}
    return {
        "checked": True,
        "valid": completed.returncode == 0,
        "error": completed.stderr.strip() or None,
    }


def file_status(destination: Path, config: dict[str, Any], tag: str) -> dict[str, Any]:
    expected = [str(item) for item in config.get("files", [])]
    marker = load_marker(destination)
    marker_files = marker.get("files", {}) if marker else {}
    files: dict[str, Any] = {}
    all_present = True
    all_hashes = True
    all_signatures = True
    for name in expected:
        path = destination / name
        present = path.is_file()
        executable = executable_ok(path) if name.endswith("helper") else present
        observed = sha256(path) if present else None
        expected_hash = marker_files.get(name, {}).get("sha256") if isinstance(marker_files, dict) else None
        hash_match = observed == expected_hash if expected_hash else False
        signature = codesign_status(path) if present and (name.endswith("helper") or name.endswith(".node") or name.endswith(".dylib")) else {"checked": False, "valid": None}
        if not present or not executable:
            all_present = False
        if not hash_match:
            all_hashes = False
        if signature.get("checked") and not signature.get("valid"):
            all_signatures = False
        files[name] = {
            "path": str(path),
            "present": present,
            "executable": executable,
            "sha256": observed,
            "matchesRecordedHash": hash_match,
            "signature": signature,
        }
    release_match = bool(marker and marker.get("release") == config.get("release") and marker.get("tag") == tag)
    ready = all_present and all_hashes and all_signatures and release_match
    return {
        "ready": ready,
        "release": marker.get("release") if marker else None,
        "marker": str(marker_path(destination)) if marker else None,
        "provenance": "verified-release" if release_match else "unknown",
        "files": files,
        "allPresent": all_present,
        "allHashesMatch": all_hashes,
        "allSignaturesValid": all_signatures,
    }


def status(repo: Path, config: dict[str, Any]) -> dict[str, Any]:
    tag, host = host_tag()
    if tag is None:
        return {
            "ready": False,
            "supported": False,
            "host": host,
            "release": config.get("release"),
            "error": {"code": host.get("code"), "message": "Pinned macOS payloads are unavailable on this host."},
        }
    destination = native_dir(repo, tag)
    details = file_status(destination, config, tag)
    return {
        "ready": details["ready"],
        "supported": True,
        "host": host,
        "release": config.get("release"),
        "asset": config.get("assets", {}).get(tag),
        "destination": str(destination),
        **details,
    }


def safe_member_path(member: str, root: str) -> str | None:
    prefix = root.rstrip("/") + "/"
    if not member.startswith(prefix):
        return None
    relative = member[len(prefix) :]
    if not relative or "/" in relative:
        return None
    return relative


def download_archive(asset: dict[str, Any], cache: Path) -> tuple[Path, bool]:
    name = str(asset["name"])
    expected = str(asset["sha256"]).lower()
    destination = cache / name
    cache.mkdir(parents=True, exist_ok=True)
    if destination.is_file() and sha256(destination) == expected:
        return destination, False
    if destination.exists():
        destination.unlink()
    partial = cache / f".{name}.{os.getpid()}.part"
    try:
        with urllib.request.urlopen(str(asset["url"]), timeout=60) as response, partial.open("wb") as output:
            while True:
                chunk = response.read(1024 * 1024)
                if not chunk:
                    break
                output.write(chunk)
        observed = sha256(partial)
        if observed != expected:
            raise RuntimeError(f"Downloaded archive digest mismatch: expected {expected}, got {observed}")
        os.replace(partial, destination)
    finally:
        partial.unlink(missing_ok=True)
    return destination, True


def install_archive(repo: Path, tag: str, config: dict[str, Any], archive: Path) -> dict[str, Any]:
    missing_licenses = [name for name in ("LICENSE", "THIRD-PARTY-NOTICES.md") if not (repo / name).is_file()]
    if missing_licenses:
        raise RuntimeError(
            "Refusing to install upstream native payloads without attribution files: "
            + ", ".join(missing_licenses)
        )
    destination = native_dir(repo, tag)
    archive_root = str(config["archiveRoot"]).rstrip("/") + "/" + tag
    names = [str(item) for item in config.get("files", [])]
    staging_parent = destination.parent
    staging_parent.mkdir(parents=True, exist_ok=True)
    staging = Path(tempfile.mkdtemp(prefix=f".{tag}-", dir=str(staging_parent)))
    try:
        with zipfile.ZipFile(archive) as bundle:
            members: dict[str, zipfile.ZipInfo] = {}
            for info in bundle.infolist():
                relative = safe_member_path(info.filename, archive_root)
                if relative is None:
                    continue
                mode = (info.external_attr >> 16) & 0xFFFF
                if stat.S_ISLNK(mode):
                    raise RuntimeError(f"Refusing symlink in native payload archive: {info.filename}")
                members[relative] = info
            missing = [name for name in names if name not in members]
            if missing:
                raise RuntimeError(f"Pinned release is missing native payload(s): {', '.join(missing)}")
            recorded: dict[str, Any] = {}
            for name in names:
                info = members[name]
                target = staging / name
                with bundle.open(info) as source, target.open("wb") as output:
                    shutil.copyfileobj(source, output)
                mode = target.stat().st_mode | stat.S_IRUSR | stat.S_IRGRP | stat.S_IROTH
                if name.endswith("helper"):
                    mode |= stat.S_IXUSR | stat.S_IXGRP | stat.S_IXOTH
                target.chmod(mode)
                recorded[name] = {"sha256": sha256(target), "size": target.stat().st_size}
        marker = {
            "schemaVersion": 1,
            "repository": config.get("repository"),
            "release": config.get("release"),
            "tag": tag,
            "archive": {
                "name": config["assets"][tag]["name"],
                "url": config["assets"][tag]["url"],
                "sha256": config["assets"][tag]["sha256"],
            },
            "installedAt": int(time.time()),
            "files": recorded,
            "license": "Upstream OpenScreen release; see repository LICENSE and THIRD-PARTY-NOTICES.md",
        }
        (staging / MARKER_NAME).write_text(json.dumps(marker, indent=2) + "\n", encoding="utf-8")
        if destination.exists() or destination.is_symlink():
            if destination.is_symlink() or not destination.is_dir():
                raise RuntimeError(f"Refusing to replace non-directory native destination: {destination}")
            backup = staging_parent / f".{tag}.previous-{os.getpid()}"
            os.replace(destination, backup)
            try:
                os.replace(staging, destination)
            except Exception:
                os.replace(backup, destination)
                raise
            shutil.rmtree(backup)
        else:
            os.replace(staging, destination)
        return file_status(destination, config, tag)
    finally:
        if staging.exists():
            shutil.rmtree(staging, ignore_errors=True)


def ensure(repo: Path, config: dict[str, Any]) -> dict[str, Any]:
    tag, host = host_tag()
    if tag is None:
        return {
            "ready": False,
            "supported": False,
            "host": host,
            "error": {"code": host.get("code"), "message": "Pinned macOS payloads are unavailable on this host."},
        }
    current = status(repo, config)
    if current.get("ready"):
        return {**current, "installed": False, "cache": str(cache_dir())}
    if os.environ.get("MEGA_RECORDER_NO_NETWORK") == "1":
        return {
            **current,
            "installed": False,
            "error": {
                "code": "NATIVE_NETWORK_DISABLED",
                "message": "Native payloads are missing and MEGA_RECORDER_NO_NETWORK=1 disables downloads.",
            },
        }
    asset = config.get("assets", {}).get(tag)
    if not isinstance(asset, dict):
        return {
            **current,
            "installed": False,
            "error": {"code": "NATIVE_ASSET_UNAVAILABLE", "message": f"No pinned asset for {tag}."},
        }
    try:
        archive, downloaded = download_archive(asset, cache_dir())
        installed = install_archive(repo, tag, config, archive)
        return {
            **status(repo, config),
            "installed": True,
            "downloaded": downloaded,
            "cache": str(cache_dir()),
            "archive": {"path": str(archive), "sha256": sha256(archive)},
            "verification": installed,
        }
    except Exception as error:
        return {
            **current,
            "installed": False,
            "error": {"code": "NATIVE_INSTALL_FAILED", "message": str(error)},
        }


def main() -> int:
    parser = argparse.ArgumentParser(description="Verify or install pinned OpenScreen macOS native payloads")
    parser.add_argument("--repo", required=True, help="MEGA RECORDER checkout")
    parser.add_argument("--ensure", action="store_true", help="download and install the pinned release when missing")
    parser.add_argument("--json", action="store_true", help="kept for explicit machine-readable invocation")
    args = parser.parse_args()
    try:
        repo = repo_path(args.repo)
        config = read_config()
        details = ensure(repo, config) if args.ensure else status(repo, config)
        payload = {"ok": bool(details.get("ready")), "command": COMMAND, "repo": str(repo), **details}
        emit(payload)
        return 0 if details.get("ready") else 1
    except (OSError, RuntimeError, ValueError) as error:
        emit({"ok": False, "command": COMMAND, "error": {"code": "NATIVE_SETUP_INVALID", "message": str(error)}})
        return 1


if __name__ == "__main__":
    raise SystemExit(main())
